### ISSUE TITLE
Trouble trying to run it

### ISSUE THREAD

**Issue by zrml** [swaggerql/swaggerql#31]
Hi & thanks for this promising and _precious_ tool!

I'm having issues trying to run it.
The installation created a directory called openapi.yaml (vs the file) I fixed that and tried to run the container I've got

```
$ docker run -it --rm -p 8000:8000 \
  -v $(pwd)/config/local.yaml:/app/config/production.yaml \
  -v $(pwd)/openapi.yaml:/app/openapi.yaml \
  swaggerql/swaggerql-mysql
yarn run v1.22.4
$ bin/swaggerql
Knex: run
$ npm install mysql --save
Cannot find module 'mysql'
Error: Cannot find module 'mysql'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Client_MySQL._driver (/app/node_modules/knex/lib/dialects/mysql/index.js:31:12)
    at Client_MySQL.initializeDriver (/app/node_modules/knex/lib/client.js:230:26)
    at Client_MySQL.Client (/app/node_modules/knex/lib/client.js:68:10)
    at new Client_MySQL (/app/node_modules/knex/lib/dialects/mysql/index.js:20:10)
    at Knex (/app/node_modules/knex/lib/knex.js:53:28)
    at Object.connect (/app/lib/query-builder/adapter/mysql2.js:4:24)
(node:28) UnhandledPromiseRejectionWarning: Error: Knex: run
```

Any help appreciated
TX

**Comment by zrml** [comment]
The postgres containers seems to run without issues; I'm OK with this. Closing it.
